version: '3.8'
services:
  redis-master:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    networks:
      - redis-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - redis-master-data:/data

  redis-replica:
    image: redis:7-alpine
    command: redis-server --replicaof redis-master 6379 --appendonly yes
    networks:
      - redis-net
    deploy:
      replicas: 2
    volumes:
      - redis-replica-data:/data

networks:
  redis-net:
    driver: overlay

volumes:
  redis-master-data:
  redis-replica-data: