version: '3.8'
services:
  # redis-master:
  #   image: redis:7-alpine
  #   command: redis-server --appendonly yes
  #   networks:
  #     - redis-net
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints: [node.role == manager]
  #   volumes:
  #     - redis-master-data:/data

  # redis-replica:
  #   image: redis:7-alpine
  #   command: redis-server --replicaof redis-master 6379 --appendonly yes
  #   networks:
  #     - redis-net
  #   deploy:
  #     replicas: 2
  #   volumes:
  #     - redis-replica-data:/data
  redis:
    image: redis:7.2.0-alpine3.18
    env_file: .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - published: 6379
        target: 6379
        protocol: tcp
        mode: ingress
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - redis-net

networks:
  redis-net:
    name: redis-net
    driver: overlay

volumes:
  redis_data:
  # redis-master-data:
  # redis-replica-data:
